/**
 * lib/watchAlertCopy.js
 *
 * Copy for the "notify me" bell emails, in every locale the site publishes in.
 * A watcher who set the bell on /es/ or /de/ gets the update in that language —
 * property_watches.locale carries it through from the moment they subscribed.
 *
 * Two things every version must do, because they are what the bell promised
 * and what makes the email worth sending:
 *   1. state plainly what changed (price moved, or the home sold out), and
 *   2. invite a reply — questions about the home or about how co-ownership
 *      works. A watcher is the warmest contact on the list: they asked to
 *      hear from us about one specific home.
 *
 * Product terminology follows docs/translation-glossary.md exactly. The word
 * for timeshare never appears in any locale.
 */

export const WATCH_COPY = {
  en: {
    subjSold: (t) => `${t} — now fully sold`,
    subjDrop: (t, p) => `Price reduced: ${t} is now ${p}`,
    subjRise: (t, p) => `Price update: ${t} is now ${p}`,
    intro: 'You asked to be told if anything changed on this home.',
    sold: (t) => `<strong>${t}</strong> is now fully sold — every share has gone.`,
    soldNext: 'Homes in the same area do come up, and shares in the best ones tend to go quietly. If you tell me what you were drawn to about this one, I can let you know first when something close to it arrives.',
    drop: (t, o, n) => `The share price of <strong>${t}</strong> has been <strong>reduced</strong> from ${o} to <strong>${n}</strong>.`,
    rise: (t, o, n) => `The share price of <strong>${t}</strong> has changed from ${o} to <strong>${n}</strong>.`,
    ask: 'Do you have any questions — about this home, or about how co-ownership works in practice? Just reply to this email and I will answer personally.',
    cta: 'View the home',
    sign: 'Dylan',
    role: 'Co-Founder · Co-Ownership Property',
    per: 'per share',
  },
  es: {
    subjSold: (t) => `${t} — ya está vendida por completo`,
    subjDrop: (t, p) => `Precio rebajado: ${t} ahora ${p}`,
    subjRise: (t, p) => `Actualización de precio: ${t} ahora ${p}`,
    intro: 'Pediste que te avisáramos si algo cambiaba en esta casa.',
    sold: (t) => `<strong>${t}</strong> ya está vendida por completo: todas las participaciones se han adjudicado.`,
    soldNext: 'Suelen salir casas parecidas en la misma zona, y las mejores participaciones se colocan discretamente. Si me cuentas qué te atrajo de esta, te aviso el primero cuando llegue algo similar.',
    drop: (t, o, n) => `El precio de la participación de <strong>${t}</strong> se ha <strong>rebajado</strong> de ${o} a <strong>${n}</strong>.`,
    rise: (t, o, n) => `El precio de la participación de <strong>${t}</strong> ha cambiado de ${o} a <strong>${n}</strong>.`,
    ask: '¿Tienes alguna duda sobre esta casa o sobre cómo funciona la copropiedad en la práctica? Responde a este correo y te contesto personalmente.',
    cta: 'Ver la casa',
    sign: 'Dylan',
    role: 'Cofundador · Co-Ownership Property',
    per: 'por participación',
  },
  fr: {
    subjSold: (t) => `${t} — entièrement vendue`,
    subjDrop: (t, p) => `Prix en baisse : ${t} passe à ${p}`,
    subjRise: (t, p) => `Mise à jour du prix : ${t} passe à ${p}`,
    intro: 'Vous aviez demandé à être prévenu si quelque chose changeait sur cette maison.',
    sold: (t) => `<strong>${t}</strong> est désormais entièrement vendue : toutes les quotes-parts sont parties.`,
    soldNext: "Des maisons comparables se libèrent régulièrement dans le secteur, et les meilleures quotes-parts partent discrètement. Dites-moi ce qui vous plaisait dans celle-ci et je vous préviendrai en premier lorsqu'une équivalente arrivera.",
    drop: (t, o, n) => `Le prix de la quote-part de <strong>${t}</strong> a été <strong>réduit</strong> de ${o} à <strong>${n}</strong>.`,
    rise: (t, o, n) => `Le prix de la quote-part de <strong>${t}</strong> est passé de ${o} à <strong>${n}</strong>.`,
    ask: "Avez-vous des questions — sur cette maison, ou sur le fonctionnement concret de la copropriété de résidence secondaire ? Répondez simplement à cet e-mail, je vous réponds personnellement.",
    cta: 'Voir la maison',
    sign: 'Dylan',
    role: 'Cofondateur · Co-Ownership Property',
    per: 'par quote-part',
  },
  de: {
    subjSold: (t) => `${t} — vollständig verkauft`,
    subjDrop: (t, p) => `Preis gesenkt: ${t} jetzt ${p}`,
    subjRise: (t, p) => `Preisänderung: ${t} jetzt ${p}`,
    intro: 'Sie wollten benachrichtigt werden, wenn sich bei dieser Immobilie etwas ändert.',
    sold: (t) => `<strong>${t}</strong> ist vollständig verkauft — alle Anteile sind vergeben.`,
    soldNext: 'In derselben Gegend kommen regelmäßig vergleichbare Häuser dazu, und die besten Anteile werden meist still vergeben. Schreiben Sie mir, was Ihnen an diesem Haus gefallen hat — dann melde ich mich als Erstes, wenn etwas Ähnliches verfügbar wird.',
    drop: (t, o, n) => `Der Preis des Miteigentumsanteils an <strong>${t}</strong> wurde von ${o} auf <strong>${n}</strong> <strong>gesenkt</strong>.`,
    rise: (t, o, n) => `Der Preis des Miteigentumsanteils an <strong>${t}</strong> hat sich von ${o} auf <strong>${n}</strong> geändert.`,
    ask: 'Haben Sie Fragen — zu dieser Immobilie oder dazu, wie Miteigentum in der Praxis funktioniert? Antworten Sie einfach auf diese E-Mail, ich antworte Ihnen persönlich.',
    cta: 'Immobilie ansehen',
    sign: 'Dylan',
    role: 'Mitgründer · Co-Ownership Property',
    per: 'pro Anteil',
  },
  it: {
    subjSold: (t) => `${t} — venduta completamente`,
    subjDrop: (t, p) => `Prezzo ridotto: ${t} ora ${p}`,
    subjRise: (t, p) => `Aggiornamento di prezzo: ${t} ora ${p}`,
    intro: 'Avevi chiesto di essere avvisato se qualcosa fosse cambiato su questa casa.',
    sold: (t) => `<strong>${t}</strong> è ora venduta completamente: tutte le quote sono state assegnate.`,
    soldNext: 'Nella stessa zona escono regolarmente case simili, e le quote migliori se ne vanno in silenzio. Dimmi che cosa ti aveva convinto di questa e ti avviso per primo quando arriva qualcosa di equivalente.',
    drop: (t, o, n) => `Il prezzo della quota di <strong>${t}</strong> è stato <strong>ridotto</strong> da ${o} a <strong>${n}</strong>.`,
    rise: (t, o, n) => `Il prezzo della quota di <strong>${t}</strong> è passato da ${o} a <strong>${n}</strong>.`,
    ask: 'Hai domande — su questa casa o su come funziona in pratica la comproprietà? Rispondi a questa email e ti rispondo personalmente.',
    cta: 'Vedi la casa',
    sign: 'Dylan',
    role: 'Cofondatore · Co-Ownership Property',
    per: 'per quota',
  },
  nl: {
    subjSold: (t) => `${t} — volledig verkocht`,
    subjDrop: (t, p) => `Prijs verlaagd: ${t} nu ${p}`,
    subjRise: (t, p) => `Prijsupdate: ${t} nu ${p}`,
    intro: 'U wilde bericht ontvangen als er iets zou veranderen aan deze woning.',
    sold: (t) => `<strong>${t}</strong> is nu volledig verkocht — alle aandelen zijn vergeven.`,
    soldNext: 'In dezelfde omgeving komen regelmatig vergelijkbare woningen bij, en de beste aandelen gaan stil weg. Laat me weten wat u in deze woning aansprak, dan bericht ik u als eerste zodra er iets soortgelijks binnenkomt.',
    drop: (t, o, n) => `De prijs van het aandeel in <strong>${t}</strong> is <strong>verlaagd</strong> van ${o} naar <strong>${n}</strong>.`,
    rise: (t, o, n) => `De prijs van het aandeel in <strong>${t}</strong> is gewijzigd van ${o} naar <strong>${n}</strong>.`,
    ask: 'Heeft u vragen — over deze woning of over hoe mede-eigendom in de praktijk werkt? Beantwoord deze e-mail gerust; ik antwoord persoonlijk.',
    cta: 'Bekijk de woning',
    sign: 'Dylan',
    role: 'Medeoprichter · Co-Ownership Property',
    per: 'per aandeel',
  },
  pt: {
    subjSold: (t) => `${t} — totalmente vendida`,
    subjDrop: (t, p) => `Preço reduzido: ${t} agora ${p}`,
    subjRise: (t, p) => `Atualização de preço: ${t} agora ${p}`,
    intro: 'Você pediu para ser avisado caso algo mudasse nesta casa.',
    sold: (t) => `<strong>${t}</strong> está totalmente vendida — todas as cotas foram adquiridas.`,
    soldNext: 'Casas parecidas aparecem com regularidade na mesma região, e as melhores cotas costumam sair discretamente. Conte o que atraiu você nesta e eu aviso em primeira mão quando surgir algo equivalente.',
    drop: (t, o, n) => `O preço da cota de <strong>${t}</strong> foi <strong>reduzido</strong> de ${o} para <strong>${n}</strong>.`,
    rise: (t, o, n) => `O preço da cota de <strong>${t}</strong> mudou de ${o} para <strong>${n}</strong>.`,
    ask: 'Tem alguma dúvida — sobre esta casa ou sobre como a multipropriedade funciona na prática? É só responder a este e-mail que eu respondo pessoalmente.',
    cta: 'Ver a casa',
    sign: 'Dylan',
    role: 'Cofundador · Co-Ownership Property',
    per: 'por cota',
  },
  sv: {
    subjSold: (t) => `${t} — nu helt såld`,
    subjDrop: (t, p) => `Sänkt pris: ${t} nu ${p}`,
    subjRise: (t, p) => `Prisuppdatering: ${t} nu ${p}`,
    intro: 'Du bad att få veta om något ändrades för det här huset.',
    sold: (t) => `<strong>${t}</strong> är nu helt såld — samtliga andelar är tagna.`,
    soldNext: 'Liknande hus dyker upp i samma område med jämna mellanrum, och de bästa andelarna går stillsamt. Berätta vad som lockade dig med det här, så hör jag av mig först när något motsvarande kommer in.',
    drop: (t, o, n) => `Priset för andelen i <strong>${t}</strong> har <strong>sänkts</strong> från ${o} till <strong>${n}</strong>.`,
    rise: (t, o, n) => `Priset för andelen i <strong>${t}</strong> har ändrats från ${o} till <strong>${n}</strong>.`,
    ask: 'Har du några frågor — om huset eller om hur samägande fungerar i praktiken? Svara bara på det här mejlet, så svarar jag personligen.',
    cta: 'Se huset',
    sign: 'Dylan',
    role: 'Medgrundare · Co-Ownership Property',
    per: 'per andel',
  },
  da: {
    subjSold: (t) => `${t} — nu helt solgt`,
    subjDrop: (t, p) => `Prisen er sat ned: ${t} nu ${p}`,
    subjRise: (t, p) => `Prisopdatering: ${t} nu ${p}`,
    intro: 'Du bad om besked, hvis der skete ændringer for denne bolig.',
    sold: (t) => `<strong>${t}</strong> er nu helt solgt — alle andele er væk.`,
    soldNext: 'Der kommer jævnligt tilsvarende boliger i samme område, og de bedste andele går stille og roligt. Fortæl mig, hvad der tiltalte dig ved denne, så giver jeg dig besked først, når noget lignende dukker op.',
    drop: (t, o, n) => `Prisen på andelen i <strong>${t}</strong> er <strong>sat ned</strong> fra ${o} til <strong>${n}</strong>.`,
    rise: (t, o, n) => `Prisen på andelen i <strong>${t}</strong> er ændret fra ${o} til <strong>${n}</strong>.`,
    ask: 'Har du spørgsmål — til boligen eller til, hvordan medejerskab fungerer i praksis? Svar blot på denne mail, så svarer jeg personligt.',
    cta: 'Se boligen',
    sign: 'Dylan',
    role: 'Medstifter · Co-Ownership Property',
    per: 'pr. andel',
  },
  no: {
    subjSold: (t) => `${t} — nå fullstendig solgt`,
    subjDrop: (t, p) => `Prisen er satt ned: ${t} nå ${p}`,
    subjRise: (t, p) => `Prisoppdatering: ${t} nå ${p}`,
    intro: 'Du ba om beskjed hvis noe endret seg for denne boligen.',
    sold: (t) => `<strong>${t}</strong> er nå fullstendig solgt — alle andeler er tatt.`,
    soldNext: 'Det kommer jevnlig tilsvarende boliger i samme område, og de beste andelene går stille. Si fra hva som tiltalte deg ved denne, så gir jeg deg beskjed først når noe liknende dukker opp.',
    drop: (t, o, n) => `Prisen på andelen i <strong>${t}</strong> er <strong>satt ned</strong> fra ${o} til <strong>${n}</strong>.`,
    rise: (t, o, n) => `Prisen på andelen i <strong>${t}</strong> er endret fra ${o} til <strong>${n}</strong>.`,
    ask: 'Har du spørsmål — om boligen eller om hvordan sameie fungerer i praksis? Bare svar på denne e-posten, så svarer jeg personlig.',
    cta: 'Se boligen',
    sign: 'Dylan',
    role: 'Medgründer · Co-Ownership Property',
    per: 'per andel',
  },
};

export const copyFor = (locale) => WATCH_COPY[locale] || WATCH_COPY.en;
